version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.9
  pre_build:
    commands:
      - pip install flake8
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - flake8 app/scr/*.py
  build:
    commands:
      - pip install -r app/scr/requirements.txt
      - docker build -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:latest
artifacts:
  files:
   - '**/*'
  name: python-app-$(date +%y%m%d%H%M).zip
